<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ShopRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|max:255',
            'address'=>'required',
            'position'=>'required',
        ];
    }

    public function attributes()
    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
        return [
            'name'=>'이름',
            'position'=>'좌표'
        ];
    }

}
