<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Support\Facades\DB;

class Review extends Pivot
{
    use HasFactory;

    protected $table = 'reviews';

    protected $fillable = [
        'name','content','score', 'user_id', 'menu_id', 'shop_id',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($review){
            $review->shop()->update([
                'score_total' => DB::raw('score_total - :score',[':score'=>$review->score]),
                'score_counts' => DB::raw('score_count - 1'),
                'score'=>DB::raw('(score_total - :score) / (score_count - 1)',[':score'=>$review->score])
            ]);
//            Shop::query()->where('id',$review->shop_id)->
        });

    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function menu(){
        return $this->belongsTo('App\Models\Menu');
    }

    public function shop(){
        return $this->belongsTo('App\Models\Shop');
    }
}
